# Array Operations

## Slicing

In [2]:
import numpy as np

In [8]:
arr = np.arange(1,10)
print("Array : ", arr)

print("Basic Slicing : ", arr[2:7])
print("Slicing with step : ", arr[2:7:2])
print("Negative indexing : ", arr[-7:-1]) #indexing always given from smaller to larger index let it be +ve or -ve indexing

Array :  [1 2 3 4 5 6 7 8 9]
Basic Slicing :  [3 4 5 6 7]
Slicing with step :  [3 5 7]
Negative indexing :  [3 4 5 6 7 8]


### slicing in matrix

In [12]:
matrix = arr.reshape((3,3))
print("Matrix : \n", matrix)

print("Accessing specific element : ", matrix[1,2]) # 1st row's 2nd element
print("Whole row : ", matrix[0])
print("Whole column : ", matrix[:, 1]) #all rows access, 1st element or column in each row


Matrix : 
 [[1 2 3]
 [4 5 6]
 [7 8 9]]
Accessing specific element :  6
Whole row :  [1 2 3]
Whole column :  [2 5 8]


## Sorting

In [24]:
#Sorting an array
unsorted = np.array([1,8,6,3,2,9,7,5,4])
print("Array sorted : ", np.sort(unsorted))

#sorting a matrix
unsortedMatrix = unsorted.reshape((3,3))
print("Unsorted Matrix : \n", unsortedMatrix)
print("Sorted matrix : \n", np.sort(unsortedMatrix, axis = 0)) #Sorts all elements in ascending order, no matter the arrangement
#Sorting by column(or sorting the individual rows)
print("Sorting by column : \n", np.sort(unsortedMatrix, axis = 1))

Array sorted :  [1 2 3 4 5 6 7 8 9]
Unsorted Matrix : 
 [[1 8 6]
 [3 2 9]
 [7 5 4]]
Sorted matrix : 
 [[1 2 4]
 [3 5 6]
 [7 8 9]]
Sorting by column : 
 [[1 6 8]
 [2 3 9]
 [4 5 7]]


## Filtering

In [27]:
arr = np.arange(10)
print("Array : ", arr)

#Direct filtering 
evenNums = arr[arr%2 == 0]
print("EVen numbers from the array : ", evenNums)

#Filtering using mask
mask = arr%2 != 0 ##Nothing just a variable holding the condition for filtering
oddNums = arr[mask]
print("Odd numbers : ", oddNums)


Array :  [0 1 2 3 4 5 6 7 8 9]
EVen numbers from the array :  [0 2 4 6 8]
Odd numbers :  [1 3 5 7 9]


### Filtering with Indexing and np.where()

In [39]:
indices = [0,2,4,6,8]
print("printing selective indices : ", arr[indices])

arr = np.arange(1,11)
print("Array : ", arr)
print("Selective indices from the array : ", arr[indices])

#where
indices = np.where(arr > 5)
print("where returns : ", indices) #indices where the given condition is true
print("Use those indices returned for filtering : ", arr[indices])

#where also takes two other argumnets
#np.where(condition, x, y)
#x or y alone cannot be passed
#x = manipulation for elements where values are true
#y = manipulation where values are false
result = np.where(arr>5, arr, 0) ##now doesn't return indices, rather manipulates the elements based on the given condition 
print("Result of where  : ", result)

printing selective indices :  [1 3 5 7 9]
Array :  [ 1  2  3  4  5  6  7  8  9 10]
Selective indices from the array :  [1 3 5 7 9]
where returns :  (array([5, 6, 7, 8, 9]),)
Use those indices returned for filtering :  [ 6  7  8  9 10]
Result of where  :  [ 0  0  0  0  0  6  7  8  9 10]


## Adding vs concatenating numoy arrays

In [45]:
arr1 = np.arange(1,6)
arr2 = np.arange(6,11)

print("Array 1 : ", arr1)
print("Array 2 : ", arr2) 
print("Sum of arrays : ", arr1 + arr2) #element wise addition

#concatenation
concatenated = np.concatenate((arr1, arr2)) #important to pass teh arrays to concatenate as a single tupple 
print("Concatenated array : ", concatenated)

Array 1 :  [1 2 3 4 5]
Array 2 :  [ 6  7  8  9 10]
Sum of arrays :  [ 7  9 11 13 15]
Concatenated array :  [ 1  2  3  4  5  6  7  8  9 10]


#### Compatibility

In [49]:
matrix1 = np.array([
    [1,2,3],
    [4,5,6],
    [7,8,9]
])

matrix2 = np.array([
    [7,8,9],
    [4,5,6],
    [1,2,3]
])

#first whether the two matrices are even compatible or not 
#compatibility : whether the two have the same shape, size, dimension, etc or not
#works on 1-D arrays too
print("Shape compatibility ; ", arr1.shape == arr2.shape)
print("Dimension compatibility : ", matrix1.ndim == matrix2.ndim)

Shape compatibility ;  True
Dimension compatibility :  True


## Adding new rows and columns

In [63]:
#The row to be added must also be a numby array
new_row = np.array([10,11,12])

#adding the row
matrix1 = np.array([
    [1,2,3],
    [4,5,6],
    [7,8,9]
])
newMatrix = np.vstack((matrix1, new_row)) #pass single tuppple
print("Added row : \n", newMatrix)

#Adding a new column
new_col = np.array([[1],[2],[3],[4]]) #separate elements to be added at the end of each row 
col_added = np.hstack((newMatrix, new_col))
print("Added column : \n", col_added)

#adding multiple columns
newCols = np.array([
    [0,1],
    [2,3],
    [3,4],
    [5,6]
])

added_cols = np.hstack((col_added, newCols))
print("Added column : \n",added_cols)

#Adding multiple rows
new_rows = np.array(
    [
        [1,2,3],
        [4,5,6],
        [7,8,9]
    ]
)

added_rows = np.vstack((matrix1, new_rows))
print("Added rows : \n",added_rows)


Added row : 
 [[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]
Added column : 
 [[ 1  2  3  1]
 [ 4  5  6  2]
 [ 7  8  9  3]
 [10 11 12  4]]
Added column : 
 [[ 1  2  3  1  0  1]
 [ 4  5  6  2  2  3]
 [ 7  8  9  3  3  4]
 [10 11 12  4  5  6]]
Added rows : 
 [[1 2 3]
 [4 5 6]
 [7 8 9]
 [1 2 3]
 [4 5 6]
 [7 8 9]]


### Deleting elements, rows and columns

In [90]:
arr = np.arange(1,11)
deleted = np.delete(arr, 4)
print("Element deleted : ", deleted)

#deleting rows or columns
#syntax : np.delete(array, index of column or row, axis (0 for row, 1 for column))
#delete row
deleted_row = np.delete(newMatrix, 2, 0)
print(newMatrix)
print(deleted_row)

#delete col
deleted_col = np.delete(newMatrix, 2, 1)
print(newMatrix)
print(deleted_col)

#deleting multiple rows/columns 
deleted_rows = np.delete(newMatrix, [1,2], 1)
print(newMatrix)
print(deleted_rows)

Element deleted :  [ 1  2  3  4  6  7  8  9 10]
[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]
[[ 1  2  3]
 [ 4  5  6]
 [10 11 12]]
[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]
[[ 1  2]
 [ 4  5]
 [ 7  8]
 [10 11]]
[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]
[[ 1]
 [ 4]
 [ 7]
 [10]]
